### ISSUE TITLE
Plone 5.2 compatibility

### ISSUE THREAD

**Issue by yurj** [collective/pas.plugins.headers#2]
https://github.com/collective/pas.plugins.headers/blob/0741c229dabb95e57c0dfaf4321dec3b470990a5/src/pas/plugins/headers/plugins.py#L4

from Globals import InitializeClass -> from AccessControl.class_init import InitializeClass

from https://zope.readthedocs.io/en/latest/zope4/migration/code.html#changed-import-paths

from Globals import InitializeClass  # OLD
from AccessControl.class_init import InitializeClass  # NEW

**Comment by mauritsvanrees** [comment]
I am fixing this in PR #3. I tried yesterday, but made a minor change in versions that tripped up Travis, so I am trying the core change now.

**Comment by mauritsvanrees** [comment]
I have released 1.0.1 with a fix for the above.
When I use Plone 5.2, the tests fail, but that seems only for the installer tests. So *should* be fine, but you should check.
Improving tests/Travis is for issue #4.

**Comment by mauritsvanrees** [comment]
More fixes in PR #5.
